version: '3'

services:
 dotnet31:
   restart: always 
   environment:
     - DOTNET_ENVIRONMENT=Production 
     - AppMerch_SecretKey=secreaqui
     - AppMerch_GatewayUrl=https://urlaqui
   build:
     context: ./
     dockerfile: Dockerfile     
   container_name: dotnet31
   command: bash -c "cp -avr . /builddotnet && cd /builddotnet && dotnet restore --force && dotnet publish MerchantIntegration.Api/MerchantIntegration.Api.csproj -o /app/out && cd /app/out && dotnet MerchantIntegration.Api.dll"
   #command: bash -c "cp -avr . /builddotnet && cd /builddotnet && dotnet restore --force && dotnet run -p MerchantIntegration.Api"
   tty: true   
   volumes:
     - ./:/app
   ports:
     - "5000:5000"
     - "5001:5001"
   depends_on:
     - mongo
   networks:
     - monitoramento-network
 mongo:
   container_name: mongodev1
   image: mongo
   ports:
     - 27017:27017
   networks:
     - monitoramento-network
 seqteste:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "655:80"
      - "5341:5341" 
    networks:
      - monitoramento-network
networks: 
    monitoramento-network:
      driver: bridge
